#version: '3.8'

name: ansible_lab 
services:
  master:
    build: ./master/
    image: ansible_master
    container_name: master01
    hostname: master01
    command: ["/usr/sbin/sshd", "-D"]
    volumes:
    - ansible_vol:/var/ans
  host:
    links:
    - master
    build: ./host/
    image: ansible_host
    container_name: host01
    hostname: host01
    ports:
      - 80
    command: ["/var/run.sh"]
    volumes:
      - ansible_vol:/var/ans
  host02:
    depends_on:
      - master
    links:
      - master
      - host
    image: ansible_host
    container_name: host02
    hostname: host02
    ports:
      - 80
    command: ["/var/run.sh"]
    volumes:
      - ansible_vol:/var/ans
  host03:
    depends_on:
      - master
    links:
      - master
      - host
    image: ansible_host
    container_name: host03
    hostname: host03
    ports:
      - 80
    command: ["/var/run.sh"]
    volumes:
      - ansible_vol:/var/ans
  host04:
    depends_on:
      - master
    links:
      - master
      - host
    image: ansible_host
    container_name: host04
    hostname: host04
    ports:
      - 80
    command: ["/var/run.sh"]
    volumes:
      - ansible_vol:/var/ans
  host05:
    depends_on:
      - master
    links:
      - master
      - host
    image: ansible_host
    container_name: host05
    hostname: host05
    ports:
      - 80
    command: ["/var/run.sh"]
    volumes:
      - ansible_vol:/var/ans
volumes:
  ansible_vol: