---
- hosts: apache
  #become: true
  vars_files:
    - vars/default.yml
 
  tasks:
    - name: apt update package
      apt: update_cache=yes

    - name: Asenna apache2
      apt:
        name: apache2
        state: present
    
    - name: käynnistä apache2
      service:
        name: apache2
        state: started
        enabled: true
    
    - name: luo webroot
      file:
        path: "/var/www/{{ http_host }}"
        state: directory
        owner: "www-data"
        mode: '0755'
    
    - name: kopioi index testi
      template:
        src: "templates/index.html.j2" # required. Path of a Jinja2 formatted template on the Ansible controller. This can be a relative or an absolute path. The file must be encoded with C(utf-8) but I(output_encoding) can be used to control the encoding of the output template.
        dest: "/var/www/omasite/index.html" # required. Location to render the template to on the remote machine.
    
    - name: virtual host 
      template:
        src: "templates/apache.conf.j2"
        dest: "/etc/apache2/sites-available/omasite.conf"

    - name: otetaan uusi site ajoon
      shell: /usr/sbin/a2ensite {{ http_conf }}
      notify: Restart Apache

    - name: oletus Apache site pois
      shell: /usr/sbin/a2dissite 000-default.conf
      when: disable_default
      notify: Reload Apache

  handlers:
    - name: Reload Apache
      service:
        name: apache2
        state: reloaded

    - name: Restart Apache
      service:
        name: apache2
        state: restarted
    
    - name: Start apache2
      service:
        name: apache2
        state: started